# Generated by Django 5.0.6 on 2024-05-27 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Day')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Available from')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Available to')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.availability')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField(verbose_name='First day')),
                ('last_day', models.DateField(verbose_name='Last day')),
                ('type', models.CharField(choices=[('a', 'Anual leave'), ('b', 'Birthday day'), ('c', 'Welness day'), ('d', 'Bussines trip')], default='a', max_length=1, verbose_name='Type of vacation')),
                ('user', models.ForeignKey(default=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
