# Generated by Django 5.0.6 on 2024-05-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Working hours')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField(verbose_name='First day')),
                ('last_day', models.DateField(verbose_name='Last day')),
                ('type', models.CharField(choices=[('a', 'Anual leave'), ('b', 'Birthday day'), ('w', 'Welness day')], default='a', max_length=1, verbose_name='Type of vacation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.user')),
            ],
        ),
    ]
