# Generated by Django 5.0.6 on 2024-06-15 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Available from')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Available to')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='schedules.availability')),
            ],
            options={
                'verbose_name': 'Available Time',
                'verbose_name_plural': 'Available Times',
            },
        ),
    ]
