# Generated by Django 5.0.6 on 2024-05-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='type',
            field=models.CharField(choices=[('a', 'Anual leave'), ('b', 'Birthday day'), ('c', 'Welness day'), ('d', 'Bussines trip')], default='a', max_length=1, verbose_name='Type of vacation'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Day')),
                ('time', models.TimeField(verbose_name='Time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.user')),
            ],
        ),
    ]
