# Generated by Django 5.0.6 on 2024-05-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_vacation_type_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='time',
        ),
        migrations.AddField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Available to'),
        ),
        migrations.AddField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Available from'),
        ),
    ]
