# Generated by Django 5.0.6 on 2024-05-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_remove_availability_time_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Available to'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Available from'),
        ),
    ]
