# Generated by Django 5.0.6 on 2024-05-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_alter_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Availability', 'verbose_name_plural': 'Availabilities'},
        ),
    ]
