# Generated by Django 5.0.6 on 2024-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_alter_user_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='working_hours',
            field=models.CharField(choices=[('1', '1 (160h/month)'), ('0.75', '0.75 (120h/month)'), ('0.5', '0.5 (80h/month)'), ('0.25', '0.25 (40h/month)'), ('1.25', '1.25 (180h/month)'), ('1.5', '1.5 (200h/month)')], default='1', max_length=4, verbose_name='Working hours'),
        ),
    ]
