# Generated by Django 5.0.6 on 2024-05-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_alter_user_working_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('dayofweek', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'last_name')},
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftassignments', to='schedules.date')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shiftassignments', to='schedules.user')),
                ('shiftname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiftassignments', to='schedules.shiftname')),
            ],
            options={
                'unique_together': {('date', 'shiftname')},
            },
        ),
    ]
