# Generated by Django 5.0.6 on 2024-05-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_date_shiftname_alter_user_options_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftassignment',
            name='date',
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='shiftname',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='ShiftName',
        ),
        migrations.DeleteModel(
            name='ShiftAssignment',
        ),
    ]
