# Generated by Django 5.0.6 on 2024-05-22 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
